import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '/styles/Home.module.css'

// Components
import NavBar from '../components/navBar'
import Hero from '../components/hero'
import Features from '../components/features'
import Contact from '../components/contact'
import About from '../components/about'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Hero/>
      <Features/>
      <Contact/>  
      <About/>
    </>
  )
}
