import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '/styles/Home.module.css'
import NavBar from '../Components/navBar/NavBar'
import Hero from '../Components/hero/hero'
import Features from '../Components/features/features'
import Contact from '../Components/contact/contact'
import Footer from '../Components/footer/footer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavBar/>
      <Hero/>
      <Features/>
      <Contact/>  
      <Footer/>
    </>
  )
}
